<script>
    const prom = new Promise(resolve => {
        setTimeout(() => resolve("この値を取り出します。"), 100);
    });

    async function asyncFunction() {
        const value = await prom;
        console.log(value);
    }

    asyncFunction();

    async function throwError() {
        try {
            await Promise.reject("Promiseが失敗しました。");
        } catch (error) {
            console.log(error);
        }
    }
    throwError();
</script> 